### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by TatsuyaOkubo** [TatsuyaOkubo/furima_28796#14]
#URL
https://furima-28796.herokuapp.com/

#Basic認証のIDとパスワード
ID : admin
パスワード : 1127

#出品者用のメールアドレスとパスワード
furima@sample.com
furima1

#購入者用のメールアドレスとパスワード
hanako@sample.com
hanako1

#購入用カードの番号・期限・セキュリティコード
番号 : 4242424242424242
期限 : 3月/23年
セキュリティコード :

**Comment by rumaruma0408** [comment]
TatsuyaOkuboさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
◯出品しようとすると以下のエラーが表示されます。
https://i.gyazo.com/b769910b5362afc85881ebea7be5f7d9.png

◯購入した商品は、再度購入できない状態になっている
→購入した商品を再度購入できてしまいます。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by TatsuyaOkubo** [comment]
出品時のエラーを解消しました。
購入した商品は再度購入できないように修正しました。

**Comment by rumaruma0408** [comment]
atsuyaOkuboさん、ご提出ありがとうございます！

◯購入用カードのセキュリティーコードの記載がないため購入に関する挙動の確認を行えておりません。

セキュリティーコードを記載次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by TatsuyaOkubo** [comment]
購入用カードのセキュリティコードが抜けていたため、再度必要情報をコメントします。

#URL
https://furima-28796.herokuapp.com/

#Basic認証のIDとパスワード
ID : admin
パスワード : 1127

#出品者用のメールアドレスとパスワード
furima@sample.com
furima1

#購入者用のメールアドレスとパスワード
hanako@sample.com
hanako1

#購入用カードの番号・期限・セキュリティコード
番号 : 4242424242424242
期限 : 3月/23年
セキュリティコード : 123

**Comment by rumaruma0408** [comment]
atsuyaOkuboさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
